### ISSUE TITLE
如何获取选定的日期

### ISSUE THREAD

**Issue by itspig** [situxinxin/LunarPickerView#2]
打搅，非常感谢您的开源代码。
请问如何获取保存时选定的日期吗，是利用 SaveBlock 吗？
`@property (nonatomic, strong) void (^saveBlock)(NSString * year,NSString * month , NSString * day);`
我是自学的 Swift ，对这个 SaveBlock 不甚了解，可否请您指点下，多谢！

**Comment by situxinxin** [comment]
是的.... 抱歉 才看到... 你使用swift调用的时候  就会出现这个
